name: delightful_toast
description: A Delightful toasbar package for rich interaction with features like slide to dismiss,auto dismiss, stacked animation and dismiss on demand.
version: 1.4.0

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
